function work_formular = fpga_parse_work_formular(work_formular_hex)

main_amp = hex2dec(work_formular_hex(1));
neighbour_amp = hex2dec(work_formular_hex(2));
third_word = uint32(hex2dec(work_formular_hex(3)));
range = uint8(bitand(third_word, 0xffu32));
n_main_amp = uint16(bitand(bitshift(third_word, -8), 0x7u32));
n_neighbour_amp = uint16(bitand(bitshift(third_word, -11), 0x1u32));
n_freq_chan = uint16(bitand(bitshift(third_word, -12), 0x1FFu32));
P_i = hex2dec(work_formular_hex(4));


work_formular = struct( ...
    'main_amp', main_amp, ...
    'neighbour_amp', neighbour_amp, ...
    'range', range, ...
    'n_main_amp', n_main_amp, ...
    'n_neighbour_amp', n_neighbour_amp, ...
    'n_freq_chan', n_freq_chan, ...
    'P_i', P_i);

end